
import Header_1 from '@/compoonents/header-1/Header_1'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header_2 from '@/compoonents/Header_2'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header_1/>
        <Header_2/>
        {children}
      </body>
    </html>
  )
}
